variable "private_subnets" {}
variable "ecs_config_bucket_arn" {}
variable "ecs_config_bucket" {}
variable "ecs_log_group" {}
variable "aws_region" {}
variable "common_tags" {}
variable "proxy_api_server_image" {}
variable "proxy_api_server_version" {}
variable "aws_security_group_ecs_api" {}
variable "aws_subnet_private_api_id" {}
variable "aws_subnet_public_api_id" {}
variable "aws_security_group_api_lb" {}
variable "vpc_id" {}