# This is a basic workflow to help you get started with Actions

name: ECS 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Checkout ECS Project
        uses: actions/checkout@v2
        with: 
          repository: sogyals429/ecs-cluster
          ssh-key: ${{secrets.SSH_KEY}}
          path: ecs-cluster

      - name: Pull Variables File
        uses: actions/checkout@v2
        with:
          repository: sogyals429/terraform_variables
          ssh-key: ${{secrets.SSH_KEY}}
          path: tf_vars

      - name: Download AWS Config
        run: '(curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip -q awscliv2.zip && sudo ./aws/install)'
        shell: sh

      - name: Setup AWS CLI
        run: 'aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY}} &&
        aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_KEY}} && aws configure set region ${{secrets.AWS_REGION}}'
        shell: sh

      - name: Install Terraform
        run: 'wget -q https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip'

      - name: Unzip Terraform Package
        run: 'unzip -o terraform_0.12.29_linux_amd64.zip && sudo mv terraform /usr/local/bin'

      - name: Init Terraform
        run: 'cd ecs-cluster && rm -rf .terraform/ && terraform init'

      - name: Deploy Project
        run: 'cd ecs-cluster && make actions'